#!/usr/bin/env bash

export FOX_VENDOR_BOOT_RECOVERY=1
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export FOX_BUILD_TYPE=Unofficial
export FOX_USE_MAGISKBOOT=1
export FOX_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export FOX_USE_LZ4_BINARY=1
export OF_USE_LZ4_COMPRESSION=1
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export OF_MAINTAINER=askell091
